Virtual height modularization
SuperDARN/pydarn pull request #190
Opened 2021-09-07 19:42 UTC by mts299

# Scope 

This is origin #187 before it was merged in by accident, I think. 

@carleyjmartin you can make your comments here that you had before.

2021-09-08 17:05 UTC, carleyjmartin commented
@francistee26 We thing the issues I've been having originated in develop branch (which Marina has just fixed!), but there's a few merge conflicts with those changes, if you want to make sure it's still doing what you want it to do with the new changes that fix the errors, I'll test again asap and we can get this into the next release :D

2021-09-08 17:38 UTC, francistee26 commented
> @francistee26 We think the issues I've been having originated in develop branch (which Marina has just fixed!), but there's a few merge conflicts with those changes, if you want to make sure it's still doing what you want it to do with the new changes that fix the errors, I'll test again asap and we can get this into the next release :D

@carleyjmartin that sounds good.

2021-09-08 18:34 UTC, francistee26 commented
> > @francistee26 We think the issues I've been having originated in develop branch (which Marina has just fixed!), but there's a few merge conflicts with those changes, if you want to make sure it's still doing what you want it to do with the new changes that fix the errors, I'll test again asap and we can get this into the next release :D
> 
> @carleyjmartin that sounds good.

@carleyjmartin I am confused as to which conflict of rtp.py you are talking about? Do you mean there is a conflict with rtp.py in the develop branch?

2021-09-08 20:01 UTC, carleyjmartin commented
@francistee26 Yeah essentially, I just mean the merge conflict stopping us from merging this branch to the current develop branch. If you're in browser on github you can resolve them just below instead of on command line which is a little easier. 

The fix for the errors that is in the current develop branch is in the same lines as some changes you made, so git doesn't know how to merge them together. (I don't know how much you do or don't know about git and using github so please tell me if you either need any help or I'm just telling you what you already know!)

We essentially just want to get that bug fix into this branch, so that we can test this branch without the errors and then merge these changes it into develop. But to do that we need to resolve the merge conflicts by telling git what the code should be.

2021-09-08 20:15 UTC, francistee26 commented
> @francistee26 Yeah essentially, I just mean the merge conflict stopping us from merging this branch to the current develop branch. If you're in browser on github you can resolve them just below instead of on command line which is a little easier.
> 
> The fix for the errors that is in the current develop branch is in the same lines as some changes you made, so git doesn't know how to merge them together. (I don't know how much you do or don't know about git and using github so please tell me if you either need any help or I'm just telling you what you already know!)
> 
> We essentially just want to get that bug fix into this branch, so that we can test this branch without the errors and then merge these changes it into develop. But to do that we need to resolve the merge conflicts by telling git what the code should be.

Hi @carleyjmartin thanks I just fixed the merge conflict.

2021-09-08 20:21 UTC, carleyjmartin commented
Great, thank you! I will test this afternoon!

2021-09-08 22:01 UTC, carleyjmartin requested changes
So when reviewing, I kinda looked at the error and tried to figure out what was going on. So you might see halfway through a comment I've figured out what is going on, I've left it as a stream of me figuring it out, so you can see where I've been looking and what errors I've been getting and why.

In addition to the issues with plot_fan, I'm also having some problem with plot_fov as this function is designed to be able to be used without data, and that the default is now coords.AACGM for some of the methods, it's unable to plot anything. 

Good news is the fix from develop worked and theres no further issue in any of the range time plots.

2021-09-10 16:29 UTC, mts299 commented
@francistee26 I am also having issues running the plot_fan code:

``` python
import pydarn
from datetime import datetime
import matplotlib.pyplot as plt 

rkn_file = 'data/20180101.0000.01.rkn.fitacf'
rkn_data = pydarn.SuperDARNRead().read_dmap(rkn_file)
pydarn.Fan.plot_fan(rkn_data, scan_index=3,
                    colorbar=False, line_color='blue',
                    radar_label=True)
````

```` bash
Traceback (most recent call last):
  File "plot_fan.py", line 20, in <module>
    radar_label=True)
  File "/home/marina/.local/lib/python3.6/site-packages/pydarn/plotting/fan.py", line 209, in plot_fan
    date=date, max_beams=None, read_file=fov_files)
  File "/home/marina/.local/lib/python3.6/site-packages/pydarn/utils/radar_pos.py", line 143, in radar_fov
    250, date))
  File "/usr/lib/python3.6/site-packages/aacgmv2-2.6.1-py3.6-linux-x86_64.egg/aacgmv2/wrapper.py", line 433, in get_aacgm_coord
    method_code=method_code)
  File "/usr/lib/python3.6/site-packages/aacgmv2-2.6.1-py3.6-linux-x86_64.egg/aacgmv2/wrapper.py", line 219, in convert_latlon
    if abs(in_lat) > 90.0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

2021-09-10 18:21 UTC, francistee26 commented
> @francistee26 I am also having issues running the plot_fan code:
> 
> ```python
> import pydarn
> from datetime import datetime
> import matplotlib.pyplot as plt 
> 
> rkn_file = 'data/20180101.0000.01.rkn.fitacf'
> rkn_data = pydarn.SuperDARNRead().read_dmap(rkn_file)
> pydarn.Fan.plot_fan(rkn_data, scan_index=3,
>                     colorbar=False, line_color='blue',
>                     radar_label=True)
> ```
> 
>  ```shell
> Traceback (most recent call last):
>   File "plot_fan.py", line 20, in <module>
>     radar_label=True)
>   File "/home/marina/.local/lib/python3.6/site-packages/pydarn/plotting/fan.py", line 209, in plot_fan
>     date=date, max_beams=None, read_file=fov_files)
>   File "/home/marina/.local/lib/python3.6/site-packages/pydarn/utils/radar_pos.py", line 143, in radar_fov
>     250, date))
>   File "/usr/lib/python3.6/site-packages/aacgmv2-2.6.1-py3.6-linux-x86_64.egg/aacgmv2/wrapper.py", line 433, in get_aacgm_coord
>     method_code=method_code)
>   File "/usr/lib/python3.6/site-packages/aacgmv2-2.6.1-py3.6-linux-x86_64.egg/aacgmv2/wrapper.py", line 219, in convert_latlon
>     if abs(in_lat) > 90.0:
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> ```
> ```

@mts299 I will take a look at it tomorrow and keep you updated.

2021-09-11 17:41 UTC, francistee26 commented on pydarn/utils/radar_pos.py
> +                                                     frang, coords = coords, reflection_height=reflection_height, height=300)
@carleyjmartin and @mts299 I was able to reproduce the error you got for plot_fan. For plot_fan to work I have it set up where you need to pass in a coord type. As regards to plot_fov I did not use that method in plot_fan I instead used radar_fov.

2021-09-11 19:48 UTC, francistee26 commented on pydarn/plotting/rtp.py
> +# https://github.com/vtsuperdarn/davitpy/blob/master/davitpyh
@carleyjmartin I did not make any changes on plot_fov. But I think in the plot_fov where the radar_fov method is called the fov_files  should be set to fov_files=fov_files for the coord Coords.AACGM if no data is used when calling the plot_fov method. I was able to make plot_fov work using plot_fov(20, datetime(2015, 3, 8, 15, 0), radar_label = True, fov_files=True) after I set the fov_files=fov_files in the radar_fov method call.

2021-09-13 15:25 UTC, carleyjmartin commented on pydarn/utils/radar_pos.py
> +                                                     frang, coords = coords, reflection_height=reflection_height, height=300)
Okay so for plot_fan, we will need to use default values in the code that doesn't break if the user doesn't give a specific set of inputs. The default coord at the moment is AACGM, which breaks the aacgm2 function it calls. Is this code not designed to be used with aacgm?

Further on from this, when specifying the coords using slant range or ground scatter mapped range, this results in a cartopy error. Is this PR supposed to introduce cartopy to the package? I thought that was going to be a different PR, and is there a back up for when the user doesn't have/doesn't want cartopy installed?

2021-09-13 16:03 UTC, carleyjmartin commented on pydarn/plotting/rtp.py
> +# https://github.com/vtsuperdarn/davitpy/blob/master/davitpyh
radar_pos and radar_fov should ideally be able to return a fov made using any of the coordinate systems, including aacgm, without needing to use the fov_files=True option right?

2021-09-15 19:46 UTC, closed without merging