FIX: Range option lower limit caused issues with indexing arrays
SuperDARN/pydarn pull request #222
Opened 2022-02-02 22:14 UTC by carleyjmartin

# Scope 

This pr includes changes made in #220 as they help fix this too. So do that one first. 

This PR is to fix the issue which occurred when `ranges=[non-zero lower limit, upper limit]`
Essentially, `ranges` is used in *radar_fov, plot_fan* and *plot_fov* as if it were an index. If it doesn't start at zero we then get a bunch of zeros at the start of the array as it was initialised as a zero array in *radar_fov*, which was indexed from `[0, ranges[1]]`. This is fixed and the plot doesn't look too crazy any more. 
In *radar_fov, plot_fan* and *plot_fov*, indexing has been changed to account for a different start:end value. For example, what was written as `[0:ranges[1]]` is now `[0:ranges[1]-ranges[0]]` (converting the `ranges` values to indexes if `ranges[0]` is non-zero). Some other arrays also needed a `-range[0]` to correct their index. 
The way that we find `good_data` in the read in file has changed to use an *np.where* so we can use two conditions, where `slist` is greater than the lowest range and less than the highest range. 
You may also see that some for loops now loop from `range(ranges[1]-ranges[0])` (to get a correct index value) but some may loop over `range(ranges[0],ranges[1])` as this is looping over the actual gate numbers not the indices. 

**issue:** to close #221 

## Approval

**Number of approvals:** 2 at least, theres quite a lot of 'thinky' changes so someone who knows the data well and can see if there's maybe some offsets or anything (like if we should be doing a -1 or +1 when looping or something, I dunno).

## Test

**matplotlib version**: 4.5.1
**Note testers: please indicate what version of matplotlib you are using**

Testing FAN:
```python
import matplotlib.pyplot as plt
import pydarn
file = '/Users/carley/Documents/data/20211008.2000.00.rkn.a.fitacf'
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()
pydarn.Fan.plot_fan(fitacf_data, grid=True, fov_color='blue',scan_index=2,
                    radar_label=True, groundscatter=True, ranges=[30,40], lowlat=50)
    
plt.show()
```
<img width="733" alt="Screen Shot 2022-02-02 at 3 48 41 PM" src="https://user-images.githubusercontent.com/60905856/152245098-b24b7155-39dc-46cf-a248-6130a9e3b308.png">

Compared to full FOV:
<img width="771" alt="Screen Shot 2022-02-02 at 3 50 03 PM" src="https://user-images.githubusercontent.com/60905856/152245389-b17b6fdf-98b4-4083-bb6f-612c45ff3435.png">

Testing some FOV:
```python
import pydarn
from datetime import datetime
import matplotlib.pyplot as plt 

fanplot=pydarn.Fan.plot_fov(66, datetime(2021, 2, 5, 12, 5), radar_location=True, radar_label=True, lowlat= 50,boundary=True, line_color='red', grid = True, rsep=15, frang=500, ranges=[0,100])
fanplot1=pydarn.Fan.plot_fov(5, datetime(2021, 2, 5, 12, 5), radar_location=True, radar_label=True,  ax=1, boundary=True, line_color='blue', grid = True, rsep=45, frang=100, ranges=[0,40])
fanplot2=pydarn.Fan.plot_fov(64, datetime(2021, 2, 5, 12, 5), radar_location=True, radar_label=True,  ax=1, boundary=True, line_color='green', grid = True, rsep=15, frang=90)
fanplot3=pydarn.Fan.plot_fov(65, datetime(2021, 2, 5, 12, 5), radar_location=True, radar_label=True,  ax=1, boundary=True, line_color='orange', grid = True)
fanplot4=pydarn.Fan.plot_fov(6, datetime(2021, 2, 5, 12, 5), radar_location=True, radar_label=True,  ax=1, boundary=True, grid = True, line_alpha=1, rsep=45, frang=0,ranges=[50,75])
plt.show()
```
![Screen Shot 2022-02-02 at 3 51 36 PM](https://user-images.githubusercontent.com/60905856/152245181-d9c928bf-ea4a-4c0c-869d-6dce9f94f772.png)

*Reminder, please check your code is:
  - copyrighted (if applicable)
  - Appropriate disclaimer added
  - Modification line filled in (if applicable)*

2022-02-08 03:05 UTC, Shirling-VT commented
MacOS 10.15.7
matplotlib 3.4.2
python 3.8.0

Both the Fan and FOV test codes provide the same results as shown. Would need more time to think about if these changes make sense or not.

2022-02-08 15:09 UTC, mts299 commented
Looks good just would merge #220 first since this contains that PR. 

@billetd do you remember why you did -1 on the lower range limit?

2022-02-08 15:10 UTC, mts299 requested changes
#220 to be merged first :)

2022-02-08 17:40 UTC, mts299 commented
@carleyjmartin I just approved it for the sake of #220 being merged... but now you need to resolve some conflicts ;)

2022-02-22 16:51 UTC, carleyjmartin commented on pydarn/plotting/fan.py
> -        hemisphere = SuperDARNRadars.radars[dmap_data[0]['stid']].hemisphere
I can't plot southern hemisphere data any more, it plots the northern hemisphere with nothing on it. This change and the kwargs['hemisphere'] change below could be the culprit.

2022-02-22 16:51 UTC, carleyjmartin commented on pydarn/plotting/fan.py
> -        kwargs['hemisphere'] = SuperDARNRadars.radars[stid].hemisphere
Second place where southern hemisphere issue could stem from?

2022-02-22 18:39 UTC, mts299 commented
@carleyjmartin can you look into this and get it working?

2022-02-22 21:10 UTC, carleyjmartin commented
Re-included the kwargs['hemisphere'] setter in the section that calls the axes for the first time and it appears to be working again.

Tested with:

``` python
pydarn.Fan.plot_fan(fitacf_data, grid=True, scan_index=2, fov_color='blue',
                    radar_label=True, groundscatter=True,ranges=[30,60])
```
and
```python                    
pydarn.Fan.plot_fan(fitacf_data, grid=True, scan_index=2, fov_color='blue',
                    radar_label=True, groundscatter=True,ranges=[30,60],coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO_COASTALINE)
 ```

For both DNC and RKN to test both hemispheres, and all appear as expected.
Let me know if there's anything else a bit off since the merge with cartopy!

2022-03-02 22:06 UTC, mts299 commented
@carleyjmartin if fix the conflicts I will re-test then hopefully merge?

2022-03-02 22:39 UTC, carleyjmartin commented
I'm very surprised that there was only one basic conflict with develop, so definitely test again, and def test on a geographic plot if you can :P

2022-03-03 15:18 UTC, mts299 commented
@carleyjmartin south works but now breaks with the cartopy addition:

``` python3
import bz2 
import pydarn
import datetime as dt
import matplotlib.pyplot as plt 

data_file = "/home/marina/superdarn/data/fitacf/20220108.0801.00.dcn.fitacf.bz2" 
with bz2.open(data_file) as fp: 
    fitacf_stream = fp.read()

data = pydarn.SuperDARNRead(fitacf_stream, True).read_fitacf()

pydarn.Fan.plot_fan(data, grid=True, scan_index=5, ranges=[20,45], fov_color='blue', radar_label=True, groundscatter=True)
plt.show()
#
pydarn.Fan.plot_fan(data, grid=True, scan_index=5, fov_color='blue', radar_label=True, groundscatter=True, coords=pydarn.Coords.GEOGRAPHIC,  projs=pydarn.Projs.GEO_COASTALINE)
plt.show()

```

``` bash
python3 test_fan.py 
resetting environment variable IGRF_COEFFS in python script
resetting environment variable AACGM_v2_DAT_PREFIX in python script
non-default coefficient files may be specified by running aacgmv2.wrapper.set_coeff_path before any other functions

IMPORTANT: Please make sure to cite pyDARN in publications that use plots created by pyDARN using DOI: https://zenodo.org/record/3727269. Citing information for SuperDARN data is found at https://pydarn.readthedocs.io/en/master/user/citing/
Traceback (most recent call last):
  File "test_fan.py", line 22, in <module>
    pydarn.Fan.plot_fan(data, grid=True, scan_index=5, fov_color='blue', radar_label=True, groundscatter=True, coords=pydarn.Coords.GEOGRAPHIC, projs=pydarn.Projs.GEO_COASTALINE)
  File "/home/marina/.local/lib/python3.8/site-packages/pydarn/plotting/fan.py", line 303, in plot_fan
    ax.pcolormesh(np.degrees(thetas), rs,
  File "/home/marina/.local/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 321, in wrapper
    return func(self, *args, **kwargs)
  File "/home/marina/.local/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 1666, in pcolormesh
    result = self._pcolormesh_patched(*args, **kwargs)
  File "/home/marina/.local/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 1702, in _pcolormesh_patched
    X, Y, C, shading = self._pcolorargs('pcolormesh', *args,
  File "/home/marina/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5575, in _pcolorargs
    raise TypeError('Dimensions of C %s are incompatible with'
TypeError: Dimensions of C (76, 16) are incompatible with X (17) and/or Y (76); see help(pcolormesh)
```

2022-03-03 15:34 UTC, carleyjmartin commented
I can't recreate the error you're finding, it's also occurring on a line that I haven't touched in this PR so it might be a bug somewhere else?

I've used:
```python
import matplotlib.pyplot as plt
import pydarn

file = '/Users/carley/Documents/data/20220108.0801.00.dcn.fitacf'
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

#pydarn.Fan.plot_fan(fitacf_data, grid=True, scan_index=2, fov_color='blue',
#                    radar_label=True, groundscatter=True, ranges=[30,60])
                    
pydarn.Fan.plot_fan(fitacf_data, grid=True, scan_index=5, fov_color='blue',
                    radar_label=True, groundscatter=True, ranges=[30,60],
                    coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO_COASTALINE)
    
plt.show()
```

and get 
![Screen Shot 2022-03-03 at 9 32 39 AM](https://user-images.githubusercontent.com/60905856/156597026-b89d8018-e557-42de-bddf-a3bda283a70f.png)

2022-03-03 20:15 UTC, mts299 commented
its weird because I only get this on this PR branch

2022-03-03 21:27 UTC, merged